// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATqTKiKGpa_1HwV3PZDc0B66yen2ijvmA',
    appId: '1:130762280175:web:566aade1c5f7efc5069f1a',
    messagingSenderId: '130762280175',
    projectId: 'dodiddone-9f6e4',
    authDomain: 'dodiddone-9f6e4.firebaseapp.com',
    storageBucket: 'dodiddone-9f6e4.appspot.com',
    measurementId: 'G-L5SD2MLVHN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4mxNqyWbubmgtKFC3vP0Q4DzkTYJ9Vjg',
    appId: '1:130762280175:ios:a80dc8c5a7e8cf2b069f1a',
    messagingSenderId: '130762280175',
    projectId: 'dodiddone-9f6e4',
    storageBucket: 'dodiddone-9f6e4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4mxNqyWbubmgtKFC3vP0Q4DzkTYJ9Vjg',
    appId: '1:130762280175:ios:a80dc8c5a7e8cf2b069f1a',
    messagingSenderId: '130762280175',
    projectId: 'dodiddone-9f6e4',
    storageBucket: 'dodiddone-9f6e4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATqTKiKGpa_1HwV3PZDc0B66yen2ijvmA',
    appId: '1:130762280175:web:da93ce57d4f0d9ac069f1a',
    messagingSenderId: '130762280175',
    projectId: 'dodiddone-9f6e4',
    authDomain: 'dodiddone-9f6e4.firebaseapp.com',
    storageBucket: 'dodiddone-9f6e4.appspot.com',
    measurementId: 'G-YD4041NF97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM7Kj0IUjdnyc12_risSh3cNqs-cZxOnU',
    appId: '1:268643627827:android:2313f4705f8ccaf521c446',
    messagingSenderId: '268643627827',
    projectId: 'dodiddone-2a9d2',
    storageBucket: 'dodiddone-2a9d2.appspot.com',
  );

}